#!/usr/bin/env python3
"""Generate config.h from .env for the bus_display Arduino sketch."""

from __future__ import annotations

from pathlib import Path
from urllib.parse import parse_qs, urlparse

ROOT = Path(__file__).parent
ENV_FILE = ROOT / ".env"
OUTPUT = ROOT / "config.h"


def parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def c_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def parse_stop_entry(raw: str) -> tuple[str, str, str, str]:
    """Return label, stopId, lineId, branchHash from a STOP_n value."""
    parts = raw.split("|")
    if len(parts) < 2:
        raise SystemExit(
            "Each STOP_n must use label|stopId|lineId|branchHash "
            "or label|full_leon_screen_url"
        )

    label = parts[0].strip()
    second = parts[1].strip()

    if second.startswith("http://") or second.startswith("https://"):
        query = parse_qs(urlparse(second).query)
    elif second.startswith("screen?"):
        query = parse_qs(second.split("?", 1)[1])
    elif len(parts) >= 4:
        return label, parts[1].strip(), parts[2].strip(), parts[3].strip()
    else:
        raise SystemExit(
            f"Invalid STOP entry for {label!r}: expected 4 pipe fields or a Leon URL"
        )

    stop_id = query.get("stopId", [""])[0]
    line_id = query.get("lineId", [""])[0]
    branch_hash = query.get("branchHash", [""])[0]

    if not stop_id or not line_id:
        raise SystemExit(
            f"Leon URL for {label!r} must include stopId and lineId query params"
        )

    return label, stop_id, line_id, branch_hash


def main() -> None:
    if not ENV_FILE.exists():
        raise SystemExit(
            f"Missing {ENV_FILE.name}. Copy .env.example to .env and fill in your values."
        )

    env = parse_env(ENV_FILE)

    for key in ("WIFI_SSID", "WIFI_PASSWORD"):
        if key not in env or not env[key]:
            raise SystemExit(f"Missing required value: {key}")

    stop_count = int(env.get("STOP_COUNT", "0"))
    stops: list[tuple[str, str, str, str]] = []
    for i in range(1, stop_count + 1):
        raw = env.get(f"STOP_{i}")
        if not raw:
            raise SystemExit(f"Missing STOP_{i}")
        stops.append(parse_stop_entry(raw))

    lines = [
        "// Auto-generated by generate_config.py — do not edit manually.",
        "#pragma once",
        "",
        f"const char* WIFI_SSID     = {c_string(env['WIFI_SSID'])};",
        f"const char* WIFI_PASSWORD = {c_string(env['WIFI_PASSWORD'])};",
        "",
        "struct Stop {",
        "  const char* label;",
        "  const char* stopId;",
        "  const char* lineId;",
        "  const char* branchHash;",
        "};",
        "",
        "Stop stops[] = {",
    ]

    for label, stop_id, line_id, branch_hash in stops:
        lines.append(
            "  { "
            f"{c_string(label)}, "
            f"{c_string(stop_id)}, "
            f"{c_string(line_id)}, "
            f"{c_string(branch_hash)} "
            "},"
        )

    lines.extend(
        [
            "};",
            "",
            "const int NB_STOPS = sizeof(stops) / sizeof(stops[0]);",
            "",
        ]
    )

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.name} ({stop_count} stop(s))")


if __name__ == "__main__":
    main()
