#!/usr/bin/env python3
"""Generate config.h from .env for the bus_display Arduino sketch."""

from pathlib import Path

ROOT = Path(__file__).parent
ENV_FILE = ROOT / ".env"
OUTPUT = ROOT / "config.h"


def parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        key, _, value = line.partition("=")
        values[key.strip()] = value.strip()
    return values


def c_string(value: str) -> str:
  return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> None:
    if not ENV_FILE.exists():
        raise SystemExit(
            f"Missing {ENV_FILE.name}. Copy .env.example to .env and fill in your values."
        )

    env = parse_env(ENV_FILE)

    for key in ("WIFI_SSID", "WIFI_PASSWORD", "PRIM_API_KEY"):
        if key not in env or not env[key]:
            raise SystemExit(f"Missing required value: {key}")

    stop_count = int(env.get("STOP_COUNT", "0"))
    stops: list[tuple[str, str, str, str, str]] = []
    for i in range(1, stop_count + 1):
        raw = env.get(f"STOP_{i}")
        if not raw:
            raise SystemExit(f"Missing STOP_{i}")
        parts = raw.split("|")
        if len(parts) < 4 or len(parts) > 5:
            raise SystemExit(
                f"STOP_{i} must use "
                "label|monitoringRef|lineFilter|directionFilter|apiLineRef format "
                "(apiLineRef is optional)"
            )
        while len(parts) < 5:
            parts.append("")
        stops.append(tuple(parts))

    lines = [
        "// Auto-generated by generate_config.py — do not edit manually.",
        "#pragma once",
        "",
        f"const char* WIFI_SSID     = {c_string(env['WIFI_SSID'])};",
        f"const char* WIFI_PASSWORD = {c_string(env['WIFI_PASSWORD'])};",
        f"const char* PRIM_API_KEY  = {c_string(env['PRIM_API_KEY'])};",
        "",
        "struct Stop {",
        "  const char* label;",
        "  const char* monitoringRef;",
        "  const char* lineFilter;",
        "  const char* directionFilter;",
        "  const char* apiLineRef;",
        "};",
        "",
        "Stop stops[] = {",
    ]

    for label, monitoring_ref, line_filter, direction_filter, api_line_ref in stops:
        lines.append(
            "  { "
            f"{c_string(label)}, "
            f"{c_string(monitoring_ref)}, "
            f"{c_string(line_filter)}, "
            f"{c_string(direction_filter)}, "
            f"{c_string(api_line_ref)} "
            "},"
        )

    lines.extend(
        [
            "};",
            "",
            "const int NB_STOPS = sizeof(stops) / sizeof(stops[0]);",
            "",
        ]
    )

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.name} ({stop_count} stop(s))")


if __name__ == "__main__":
    main()
